import type { TemplateDocument, TemplateTokens } from "./templateTypes";

const now = "2026-05-14T00:00:00.000Z";

export const defaultTemplateTokens: TemplateTokens = {
  colors: {
    canvas: "#f6f7fb",
    surface: "#ffffff",
    surfaceMuted: "#eef2f7",
    text: "#172033",
    textMuted: "#637083",
    primary: "#2563eb",
    accent: "#16a34a",
    warning: "#f59e0b",
    border: "#d8dee9",
  },
  typography: {
    display: {
      fontFamily: "Inter, system-ui, sans-serif",
      fontSize: 48,
      fontWeight: 800,
      lineHeight: 1.05,
      letterSpacing: 0,
    },
    title: {
      fontFamily: "Inter, system-ui, sans-serif",
      fontSize: 28,
      fontWeight: 700,
      lineHeight: 1.16,
      letterSpacing: 0,
    },
    body: {
      fontFamily: "Inter, system-ui, sans-serif",
      fontSize: 16,
      fontWeight: 400,
      lineHeight: 1.5,
      letterSpacing: 0,
    },
    label: {
      fontFamily: "Inter, system-ui, sans-serif",
      fontSize: 13,
      fontWeight: 600,
      lineHeight: 1.25,
      letterSpacing: 0,
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 40,
    "2xl": 64,
  },
  radii: {
    sm: 4,
    md: 8,
    lg: 12,
    pill: 999,
  },
  shadows: {
    soft: "0 18px 45px rgba(23, 32, 51, 0.12)",
    crisp: "0 1px 3px rgba(23, 32, 51, 0.16)",
  },
};

export const seedTemplates: TemplateDocument[] = [
  {
    metadata: {
      id: "template-dashboard-ops",
      name: "Painel Operacional",
      description: "Template para dashboards administrativos com indicadores, tabela e area de acompanhamento.",
      category: "dashboard",
      status: "published",
      tags: ["dashboard", "admin", "metricas"],
      createdAt: now,
      updatedAt: now,
    },
    canvas: {
      width: 1440,
      height: 1024,
      preset: "desktop",
      background: defaultTemplateTokens.colors.canvas,
      gridSize: 8,
    },
    tokens: defaultTemplateTokens,
    layers: [
      {
        id: "dash-shell",
        name: "Estrutura",
        type: "frame",
        bounds: { x: 0, y: 0, width: 1440, height: 1024 },
        visible: true,
        style: { fill: defaultTemplateTokens.colors.canvas },
        children: [
          {
            id: "dash-sidebar",
            name: "Menu lateral",
            type: "shape",
            shape: "rectangle",
            bounds: { x: 0, y: 0, width: 256, height: 1024 },
            visible: true,
            style: { fill: "#111827" },
          },
          {
            id: "dash-title",
            name: "Titulo",
            type: "text",
            content: "Visao geral",
            bounds: { x: 304, y: 64, width: 360, height: 56 },
            visible: true,
            textStyle: { ...defaultTemplateTokens.typography.title, color: defaultTemplateTokens.colors.text },
          },
          {
            id: "dash-card-primary",
            name: "Card receita",
            type: "shape",
            shape: "rectangle",
            bounds: { x: 304, y: 152, width: 320, height: 160 },
            visible: true,
            style: { fill: "#ffffff", radius: 8, shadow: defaultTemplateTokens.shadows.crisp },
          },
          {
            id: "dash-card-secondary",
            name: "Card pedidos",
            type: "shape",
            shape: "rectangle",
            bounds: { x: 648, y: 152, width: 320, height: 160 },
            visible: true,
            style: { fill: "#ffffff", radius: 8, shadow: defaultTemplateTokens.shadows.crisp },
          },
          {
            id: "dash-table",
            name: "Tabela",
            type: "shape",
            shape: "rectangle",
            bounds: { x: 304, y: 352, width: 1040, height: 560 },
            visible: true,
            style: { fill: "#ffffff", radius: 8, shadow: defaultTemplateTokens.shadows.crisp },
          },
        ],
      },
    ],
  },
  {
    metadata: {
      id: "template-catalog-showcase",
      name: "Catalogo de Produtos",
      description: "Vitrine responsiva para catalogos comerciais com destaque, filtros e cards de produto.",
      category: "catalog",
      status: "published",
      tags: ["catalogo", "produtos", "vitrine"],
      createdAt: now,
      updatedAt: now,
    },
    canvas: {
      width: 1280,
      height: 960,
      preset: "desktop",
      background: "#fbfcfe",
      gridSize: 8,
    },
    tokens: defaultTemplateTokens,
    layers: [
      {
        id: "catalog-hero",
        name: "Hero catalogo",
        type: "frame",
        bounds: { x: 0, y: 0, width: 1280, height: 960 },
        visible: true,
        style: { fill: "#fbfcfe" },
        children: [
          {
            id: "catalog-band",
            name: "Faixa principal",
            type: "shape",
            shape: "rectangle",
            bounds: { x: 0, y: 0, width: 1280, height: 320 },
            visible: true,
            style: { fill: "#e8f0ff" },
          },
          {
            id: "catalog-title",
            name: "Titulo catalogo",
            type: "text",
            content: "Colecao em destaque",
            bounds: { x: 80, y: 96, width: 520, height: 64 },
            visible: true,
            textStyle: { ...defaultTemplateTokens.typography.display, color: defaultTemplateTokens.colors.text },
          },
          {
            id: "catalog-grid-a",
            name: "Produto A",
            type: "shape",
            shape: "rectangle",
            bounds: { x: 80, y: 392, width: 260, height: 360 },
            visible: true,
            style: { fill: "#ffffff", radius: 8, shadow: defaultTemplateTokens.shadows.crisp },
          },
          {
            id: "catalog-grid-b",
            name: "Produto B",
            type: "shape",
            shape: "rectangle",
            bounds: { x: 372, y: 392, width: 260, height: 360 },
            visible: true,
            style: { fill: "#ffffff", radius: 8, shadow: defaultTemplateTokens.shadows.crisp },
          },
          {
            id: "catalog-grid-c",
            name: "Produto C",
            type: "shape",
            shape: "rectangle",
            bounds: { x: 664, y: 392, width: 260, height: 360 },
            visible: true,
            style: { fill: "#ffffff", radius: 8, shadow: defaultTemplateTokens.shadows.crisp },
          },
        ],
      },
    ],
  },
  {
    metadata: {
      id: "template-mobile-flow",
      name: "Fluxo Mobile",
      description: "Base mobile para telas de onboarding, formulario e confirmacao.",
      category: "mobile",
      status: "draft",
      tags: ["mobile", "app", "onboarding"],
      createdAt: now,
      updatedAt: now,
    },
    canvas: {
      width: 390,
      height: 844,
      preset: "mobile",
      background: "#ffffff",
      gridSize: 4,
    },
    tokens: defaultTemplateTokens,
    layers: [
      {
        id: "mobile-root",
        name: "Tela mobile",
        type: "frame",
        bounds: { x: 0, y: 0, width: 390, height: 844 },
        visible: true,
        style: { fill: "#ffffff" },
        children: [
          {
            id: "mobile-visual",
            name: "Area visual",
            type: "shape",
            shape: "rectangle",
            bounds: { x: 24, y: 56, width: 342, height: 280 },
            visible: true,
            style: { fill: "#e9f8ef", radius: 12 },
          },
          {
            id: "mobile-heading",
            name: "Chamada",
            type: "text",
            content: "Organize seu projeto",
            bounds: { x: 24, y: 392, width: 342, height: 72 },
            visible: true,
            textStyle: { ...defaultTemplateTokens.typography.title, color: defaultTemplateTokens.colors.text },
          },
          {
            id: "mobile-button",
            name: "Botao principal",
            type: "shape",
            shape: "rectangle",
            bounds: { x: 24, y: 736, width: 342, height: 56 },
            visible: true,
            style: { fill: defaultTemplateTokens.colors.primary, radius: 8 },
          },
        ],
      },
    ],
  },
];
